/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    BattlePass: typeof import('./src/components/BattlePass.vue')['default']
    DailyTaskSettings: typeof import('./src/components/DailyTaskSettings.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    PassTaskSettings: typeof import('./src/components/PassTaskSettings.vue')['default']
    RewardSettings: typeof import('./src/components/RewardSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeeklyTaskSettings: typeof import('./src/components/WeeklyTaskSettings.vue')['default']
  }
}
